### ISSUE TITLE
I can't use "summary" function 

### ISSUE THREAD

**Issue by wzw14541** [cran/SimRVSequences#1]
Hi

When I used "summary" function with example data,  it didn't work  and  this function seems didn't exist in "SimRVSequences" R packages.I also tried command "SimRVSequences::summary" but  it also didn't work .
So , I want to know the correct way to use this function.

Thanks

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
